# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Object files.
o_ArbInt = env.Object(target = 'ArbInt', source = ['ArbInt.cxx'])

# Create a dictionary containing all necessary information and objects to
# compile with ArbInt.
cArbInt = { 'obj': [o_ArbInt], 'include': ['ArbInt'], 'defines': [] }

# Return.
Return('cArbInt')