# Imports.
from sconsgeneral import Module

# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Create our module definiton.
ctrim            = Module()
ctrim.own_module = 'trim'

# Headers.
ctrim.own_include = 'trim'
ctrim.own_headers = ['trim.h++']

# Object files.
o_trim = env.Object      (target = 'trim', source = ['trim.c++'])
s_trim = env.SharedObject(target = 'trim', source = ['trim.c++'])
ctrim.own_objects        = [o_trim]
ctrim.own_shared_objects = [s_trim]

# Return.
Return('ctrim')
