# Imports.
from sconsgeneral import Module

# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Create our module definition.
cwrapText            = Module()
cwrapText.own_module = 'wrapText'

# Headers.
cwrapText.own_include = 'wrapText'
cwrapText.own_headers = ['wrapText.h++']

# Object files.
o_wrapText = env.Object      (target = 'wrapText', source = ['wrapText.c++'])
s_wrapText = env.SharedObject(target = 'wrapText', source = ['wrapText.c++'])
cwrapText.own_objects        = [o_wrapText]
cwrapText.own_shared_objects = [s_wrapText]

# Return.
Return('cwrapText')
