# Imports.
from sconsgeneral import Module

# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Create our module definiton.
ctokenize            = Module()
ctokenize.own_module = 'tokenize'

# Headers.
ctokenize.own_include = 'tokenize'
ctokenize.own_headers = ['tokenize.h++']

# Object files.
o_tokenize = env.Object      (target = 'tokenize', source = ['tokenize.c++'])
s_tokenize = env.SharedObject(target = 'tokenize', source = ['tokenize.c++'])
ctokenize.own_objects        = [o_tokenize]
ctokenize.own_shared_objects = [s_tokenize]

# Return.
Return('ctokenize')
