# Imports.
from sconsgeneral import Module

# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Create our module definition.
cUArbInt = Module()

# Headers.
cUArbInt.own_include = 'UArbInt'
cUArbInt.own_headers = ['UArbInt.h++']

# Object files.
o_UArbInt = env.Object      (target = 'UArbInt', source = ['UArbInt.c++'])
s_UArbInt = env.SharedObject(target = 'UArbInt', source = ['UArbInt.c++'])
cUArbInt.own_objects        = [o_UArbInt]
cUArbInt.own_shared_objects = [s_UArbInt]

# Return.
Return('cUArbInt')
