# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Create program-specific environments.
env_ArbInt = env.Copy()
for incdir in cArbInt['include'] : env_ArbInt.Append(CPPPATH    = ['#' + incdir])
for define in cArbInt['defines'] : env_ArbInt.Append(CPPDEFINES = [ define ])
env_Arb = env.Copy()
for incdir in cArb['include'] : env_Arb.Append(CPPPATH    = ['#' + incdir])
for define in cArb['defines'] : env_Arb.Append(CPPDEFINES = [ define ])
env_Timestamp = env.Copy()
for incdir in cTimestamp['include'] : env_Timestamp.Append(CPPPATH    = ['#' + incdir])
for define in cTimestamp['defines'] : env_Timestamp.Append(CPPDEFINES = [ define ])
env_File = env.Copy()
for incdir in cFile['include'] : env_File.Append(CPPPATH    = ['#' + incdir])
for define in cFile['defines'] : env_File.Append(CPPDEFINES = [ define])

# Object files.
o_SafeInt   = env          .Object(target = 'SafeInt',   source = ['SafeInt.cxx']  )
o_ArbInt    = env_ArbInt   .Object(target = 'ArbInt',    source = ['ArbInt.cxx']   )
o_Arb       = env_Arb      .Object(target = 'Arb',       source = ['Arb.cxx']      )
o_Timestamp = env_Timestamp.Object(target = 'Timestamp', source = ['Timestamp.cxx'])
o_File      = env_File     .Object(target = 'File',      source = ['File.cxx']     )
o_float     = env          .Object(target = 'float',     source = ['float.cxx']    )

# Programs.
env          .Program(target = 'SafeInt',   source = [o_SafeInt]                            )
env_ArbInt   .Program(target = 'ArbInt',    source = list(cArbInt['obj'])    + [o_ArbInt]   )
env_Arb      .Program(target = 'Arb',       source = list(cArb['obj'])       + [o_Arb]      )
env_Timestamp.Program(target = 'Timestamp', source = list(cTimestamp['obj']) + [o_Timestamp])
env_File     .Program(target = 'File',      source = list(cFile['obj'])      + [o_File]     )
env          .Program(target = 'float',     source = [o_float]                              )
