# Imports.
from sconsgeneral import Module

# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Module definition.
putilities            = Module()
putilities.own_module = 'utilities'

# Object files.
o_longDiv = env.Object(target = 'longDiv', source = ['longDiv.c++']); putilities.own_objects.append(o_longDiv)

# Programs.
putilities.own_programs.append(env.Program(target = 'longDiv', source = [o_longDiv]))

Return('putilities')
