# Imports from caller.
Import('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Object files.
o_POSIXFile = env.Object      (target = 'POSIXFile', source = ['POSIXFile.c++'])
s_POSIXFile = env.SharedObject(target = 'POSIXFile', source = ['POSIXFile.c++'])

# Create a dictionary containing all necessary information and objects to
# compile with POSIXFile.
cPOSIXFile = { 'obj'        : [o_POSIXFile]              ,
               'sobj'       : [s_POSIXFile]              ,
               'include'    : ['POSIXFile']              ,
               'headers'    : ['POSIXFile/POSIXFile.h++'],
               'defines'    : []                         ,
               'own_obj'    : [o_POSIXFile]              ,
               'own_sobj'   : [s_POSIXFile]              ,
               'own_include': 'POSIXFile'                ,
               'own_headers': ['POSIXFile/POSIXFile.h++'],
               'own_defines': []                           }

# Return.
Return('cPOSIXFile')
