import os

env = Environment(
	ENV = os.environ,
	CPPPATH = [
		'.',
		'..'
	],
	tools = [
		'mingw',
		'gcc'
	]
)

if (env['CC'] == 'gcc') :
	env.Append(
		CCFLAGS = '-g -O0 -ansi -w'
	)

Arbitrary = env.Object(target = 'Arbitrary', source = [ 'Arbitrary.cxx' ])
main      = env.Object(target = 'main',      source = [ 'test.cxx'      ])

env.Program(
	target = 'Arbitrary',
	source = [
		main,
		Arbitrary
	]
)