# Imports from caller.
Import ('*')

# Include the parent directory.
env.Append(CPPPATH = ['..'])

# Object files.
o_Syslog = env.Object      (target = 'Syslog', source = ['Syslog.c++'])
s_Syslog = env.SharedObject(target = 'Syslog', source = ['Syslog.c++'])

# Create a dictionary containing all necessary information and objects to
# compile with Syslog.
cSyslog = { 'obj'         : [o_Syslog]           ,
            'sobj'        : [s_Syslog]           ,
            'include'     : ['Syslog']           ,
            'headers'     : ['Syslog/Syslog.h++'],
            'defines'     : []                   ,
            'own_obj'     : [o_Syslog]           ,
            'own_sobj'    : [s_Syslog]           ,
            'own_include' : 'Syslog'             ,
            'own_headers' : ['Syslog/Syslog.h++'],
            'own_defines' : []                     }

# Return.
Return('cSyslog')
